### Bibliotecas

In [2]:
import pandas as pd
import numpy as np
from deltalake import DeltaTable
from deltalake.writer import write_deltalake

### Dataframe Pandas

In [3]:
df = pd.read_csv("./data/petlove_consumer.csv")

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  10000 non-null  object
 1   created_at          10000 non-null  object
 2   updated_at          10000 non-null  object
 3   deleted_at          505 non-null    object
 4   name_hash           10000 non-null  object
 5   email_hash          10000 non-null  object
 6   address_hash        10000 non-null  object
 7   birth_date          10000 non-null  object
 8   status              10000 non-null  object
 9   version             10000 non-null  object
 10  city                10000 non-null  object
 11  state               10000 non-null  object
 12  neighborhood        10000 non-null  object
 13  last_date_purchase  10000 non-null  object
 14  average_ticket      10000 non-null  float64
 15  items_quantity      10000 non-null  int64
 16  all_revenue         10000 non-null  float64
 17  all_orders          10000 non-null  int64
 18  recency             10000 non-null  int64
 19  marketing_source    10000 non-null  object
dtypes: float64(2), int64(3), object(15)
memory usage: 1.5+ MB

In [6]:
df.head()

,id,created_at,updated_at,deleted_at,name_hash,email_hash,address_hash,birth_date,status,version,city,state,neighborhood,last_date_purchase,average_ticket,items_quantity,all_revenue,all_orders,recency,marketing_source
0,8bf7960e-3b93-468b-856e-6c6c5b56f52b,08/15/17 07:05 AM,01/14/21 11:23 AM,NaN,312d206168a318614897e8ccac43bff9,83eb3aed9a44377df80ce876dce92c9a,8b4bfaa0cbc41a16f46da15ddcd6a907,07/10/74 12:00 AM,active,2.31.7,Peixoto da Praia,AM,Aparecida 7ª Seção,01/14/21 11:23 AM,151.142942,10,906.857651,6,35,crm
1,a39535b5-4647-4680-b4f6-3aed57c1f1ff,12/31/19 09:53 PM,01/08/21 11:23 AM,NaN,de448fcb47d0d6a873b2eef52b5ee595,72678bb35e2ac84ed373e81dd9dca28c,22f1cfa1847f38da3f3cb114dd2b9247,07/06/40 12:00 AM,paused,3.30.12,Fernandes,RR,Santa Isabel,01/08/21 11:23 AM,236.991790,4,236.991790,1,41,organic_search
2,dc067cd2-c021-42bd-8c0e-beb267280e66,03/07/19 11:46 PM,01/07/21 11:23 AM,NaN,cb09e447ddc38283373d56bb46498e6a,668f4ee9add29c7bd02c485f1b7509e3,6cb47446a086ee6483b3eb954f11467a,03/18/63 12:00 AM,active,3.28.9,Lopes,RR,Estrela,01/07/21 11:23 AM,211.955597,13,2331.511572,11,42,organic_search
3,b5e4caeb-3a9b-49ed-aa33-5acd06b162c1,07/21/18 10:17 AM,01/10/21 11:23 AM,NaN,52593437a405b11b3557170680ef80c8,d3fb45188d95c8d7cc49da5b4f727c86,0a6f0c54db1e6f19347f96b50f8092a4,11/21/80 12:00 AM,active,3.34.3,Campos do Campo,PE,Confisco,01/10/21 11:23 AM,204.113227,8,1224.679359,6,39,organic_search
4,d4ff61fc-f008-4e19-b8ae-bd70cfa3ae27,06/08/18 12:09 PM,01/18/21 11:23 AM,NaN,dbda4b778a966c21904238ed2d2005db,a0f76bc49b4c43327b536da6e1a1465e,143b9f169b4fa1692f6d79b5682169b5,07/07/59 12:00 AM,active,3.19.8,das Neves,RJ,Vila Suzana Segunda Seção,01/18/21 11:23 AM,252.940997,9,2023.527980,8,31,crm

### Dataframe DeltaTable

### Transformando o arquivo CSV em Delta

In [11]:
write_deltalake('./data/deltalake/petlove_consumer', df,
                description="Um teste para transformar o csv da petlove em um formato Delta Table",
                partition_by=['state'])

### Lendo o Arquivo em formato Delta

In [13]:
dt = DeltaTable("./data/deltalake/petlove_consumer").to_pandas()

In [14]:
dt

,id,created_at,updated_at,deleted_at,name_hash,email_hash,address_hash,birth_date,status,version,city,state,neighborhood,last_date_purchase,average_ticket,items_quantity,all_revenue,all_orders,recency,marketing_source
0,d4ff61fc-f008-4e19-b8ae-bd70cfa3ae27,06/08/18 12:09 PM,01/18/21 11:23 AM,None,dbda4b778a966c21904238ed2d2005db,a0f76bc49b4c43327b536da6e1a1465e,143b9f169b4fa1692f6d79b5682169b5,07/07/59 12:00 AM,active,3.19.8,das Neves,RJ,Vila Suzana Segunda Seção,01/18/21 11:23 AM,252.940997,9,2023.527980,8,31,crm
1,48c5e611-835d-4aad-9a42-114dfd93c01b,07/17/16 10:30 AM,01/11/21 11:23 AM,None,480c8dbeaf38e36b7eaa4914ff12b4d6,41e7fbe139022b240f143beda7acef9b,c3642b7d1c9e2f4978f21bf38c05b771,08/22/67 12:00 AM,active,5.22.8,da Mota da Prata,RJ,Vila Independencia 1ª Seção,01/11/21 11:23 AM,239.507793,5,1676.554553,7,38,crm
2,0bd41d8e-a514-40b2-95f2-7c258e595528,07/28/20 04:55 PM,01/15/21 11:23 AM,None,fe898fef9dbc400f7f4dd417374b1fc6,36028fcb99796f455f7690eb3d44850e,4ad922b22fdc90748383347fa2d0783f,12/07/92 12:00 AM,active,5.2.8,da Cunha de Cavalcanti,RJ,Caetano Furquim,01/15/21 11:23 AM,228.126182,9,1368.757094,6,34,organic_search
3,ec24d488-7778-4207-8f2d-10eca4c49944,04/01/16 01:08 PM,01/14/21 11:23 AM,None,5f00aec80b809660424a08721d9480d2,ac54707934f69934b8a6cdfa93730554,5651a39c86f528f0f5c5bc78b04a3241,07/05/64 12:00 AM,active,4.37.15,Silva da Serra,RJ,Horto Florestal,01/14/21 11:23 AM,200.291298,7,2002.912982,10,35,direct
4,35607577-327c-4c23-be32-5a33317a34fb,09/16/17 10:38 PM,01/13/21 11:23 AM,None,ae827a37e75c7af3778f2e3eb6c2b439,de4e18ae5cbd2fe16c88d821993414c3,b96198ac4d6b398ad7437489f2ed744e,07/23/73 12:00 AM,active,1.23.10,Barbosa,RJ,Vila Tirol,01/13/21 11:23 AM,219.349241,7,1096.746205,5,36,direct
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,b53f4838-c8f7-4262-b6f2-3a4a10de64e0,05/12/17 04:48 PM,01/23/21 11:23 AM,None,e14bd05995cf5a88809ec3d8b9fc39f8,22244b3a1ae7077d0380513b41055d86,68647fd9780ca32626b361ce7ad24abe,06/20/93 12:00 AM,active,3.18.13,Pinto,DF,Vila Satélite,01/23/21 11:23 AM,208.597723,11,1877.379507,9,26,organic_search
9996,baae8960-6a11-48c0-8282-ac0fdddc1e9d,03/28/18 11:53 PM,01/19/21 11:23 AM,None,f9a008df53a434cd64b17a2898106a85,dd860b3785e0d5c4bbf87b979149e394,29e5d9df295de05d96de865b115bf9bc,06/25/93 12:00 AM,active,3.-5.8,Barros,DF,São Salvador,01/19/21 11:23 AM,163.434930,10,1634.349301,10,30,direct
9997,6653a1a2-5ef8-482f-9105-530ce7c57e98,06/21/17 11:42 PM,01/22/21 11:23 AM,None,34acaab8042b8273b82119170c32a674,5a7017013ee2b4b5b48e76f6f01ee937,9881ebd83557d231925abd5f6e0e7601,11/16/82 12:00 AM,paused,3.20.9,Novaes,DF,Conjunto Providencia,01/22/21 11:23 AM,231.158574,6,1618.110015,7,27,direct
9998,f55ce7c3-fa5f-43b4-9d09-61ceb06f4ba1,04/14/17 04:53 AM,01/24/21 11:23 AM,None,257f7b44bbdac81ad53559d6a6c78f9c,4bcd40c3685b0666f9b43ec0f397616c,767172d384d131c1e9766ee6fcb9c224,02/05/90 12:00 AM,active,4.33.7,Porto,DF,Unidas,01/24/21 11:23 AM,199.664231,5,1996.642306,10,25,organic_search
9999,d82c35e5-967a-4136-8355-e1b2be31e1ca,02/11/21 08:04 PM,01/20/21 11:23 AM,None,b3ae3ec3e01c3563b7e044a426179c22,9bef0c339da161bbb7fb3528cf397735,9ea53c69e60aef7b4df0235584599e30,10/29/68 12:00 AM,active,2.27.2,Rodrigues,DF,Bairro Das Indústrias Ii,01/20/21 11:23 AM,214.283045,8,0.000000,0,29,none